version: '3.8'
services:
  ffc-pay-statement-generator:
    build:
      context: .
      target: production
    image: ffc-pay-statement-generator
    container_name: ffc-pay-statement-generator
    depends_on:
      - ffc-pay-statement-azurite
      - ffc-pay-statement-generator-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-statement-generator-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}      
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      STATEMENT_TOPIC_ADDRESS: ${STATEMENT_TOPIC_ADDRESS:-ffc-pay-statements}${MESSAGE_QUEUE_SUFFIX}
      STATEMENT_SUBSCRIPTION_ADDRESS: ${STATEMENT_SUBSCRIPTION_ADDRESS:-ffc-pay-statement-generator}${MESSAGE_QUEUE_SUFFIX}
      PUBLISH_TOPIC_ADDRESS: ${PUBLISH_TOPIC_ADDRESS:-ffc-pay-statement-publish}${MESSAGE_QUEUE_SUFFIX}
      CRM_TOPIC_ADDRESS: ${CRM_TOPIC_ADDRESS:-ffc-pay-statement-crm}${MESSAGE_QUEUE_SUFFIX}
      POSTGRES_DB: ffc_pay_statement_generator
      POSTGRES_HOST: ${POSTGRES_HOST:-ffc-pay-statement-generator-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME:-devstoreaccount1}
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"
      FFC_API_PATH: ffcApi
      STATEMENT_RECEIVER_ENDPOINT: http://ffc-pay-statement-receiver

  ffc-pay-statement-generator-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_pay_statement_generator
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres

  ffc-pay-statement-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.17.1
    command: "azurite-blob --loose --blobHost 0.0.0.0"
    labels:
      com.docker.compose.pay.role: ffc-pay-statement-azurite
