services:
  ffc-pay-statement-generator:
    build:
      context: .
      target: production
    image: ffc-pay-statement-generator
    container_name: ffc-pay-statement-generator
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-statement-generator-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
