environment: development
environmentCode:
name: ffc-pay-statement-generator
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-statement-generator

labels: {}

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-pay-statement-generator-config-map

containerSecret:
  name: ffc-pay-statement-generator-container-secret
  type: Opaque

deployment:
  minReplicas: 1
  maxReplicas: 8
  cpuThreshold: 80
  memoryThreshold: 80

container:
  requestMemory: 150Mi
  requestCpu: 120m
  limitMemory: 150Mi
  limitCpu: 120m
  messageQueueHost: namespace.servicebus.windows.net
  statementTopicAddress: ffc-pay-statements
  statementSubscriptionAddress: ffc-pay-statement-generator
  publishTopicAddress: ffc-pay-statement-publish
  crmTopicAddress: ffc-pay-statement-crm
  azureStorageAccountName: ffcpay
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  azureStorageCreateContainers: false
  storageContainer: statements
  storageFolder: outbound
  statementReceiverApiVersion: v1
  statementReceiverEndpoint: https://ffc-pay-statement-receiver
  schedulesArePublished: false

ingress:
  server: example.com

postgresService:
  postgresDb: ffc_pay_statement_generator
  postgresqlHost: ffc-pay-statement-generator-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
