environment: development
name: ffc-pay-statement-generator
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-statement-generator

labels: {}

appInsights:
  key:

containerConfigMap:
  name: ffc-pay-statement-generator-config-map

containerSecret:
  name: ffc-pay-statement-generator-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReplicas: 1
  maxReplicas: 1
  cpuThreshold: 80
  memoryThreshold: 80
  minReadySeconds: 0

container:
  imagePullPolicy: Always
  requestMemory: 150Mi
  requestCpu: 120m
  limitMemory: 150Mi
  limitCpu: 180m
  messageQueueHost: namespace.servicebus.windows.net
  statementTopicAddress: ffc-pay-statements
  statementSubscriptionAddress: ffc-pay-ffc-pay-statement-generator
  azureStorageAccountName: ffcpay
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  azureStorageCreateContainers: false
  storageContainer: statements
  storageFolder: outbound

postgresService:
  postgresDb: ffc_pay_statement_generator
  postgresqlHost: ffc-pay-statement-generator-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
