const advancePaymentHelp = require('../../../../../../../app/generator/content/advance-payment-help')

describe('advancedPaymentHelp', () => {
  it('should return the correct advanced payment help page', () => {
    const result = advancePaymentHelp()

    expect(result).toHaveProperty('style', 'govuk-body-s')
    expect(result).toHaveProperty('stack')
    expect(result.stack[0]).toHaveProperty('text', '\n')
    expect(result.stack[1]).toHaveProperty('text', 'More information')
    expect(result.stack[2]).toHaveProperty('text', 'If you think your payments are wrong, you should:')
    expect(result.stack[3]).toHaveProperty('ul')
    expect(result.stack[3]).toHaveProperty('text', 'log into the Rural Payments service')
    expect(result.stack[3]).toHaveProperty('text', 'www.gov.uk/claim-rural-payments')
    expect(result.stack[3]).toHaveProperty('link', 'https://www.gov.uk/claim-rural-payments')
    expect(result.stack[3]).toHaveProperty('text', ' to check your SFI standard agreement')
    expect(result.stack[4]).toHaveProperty('text', 'check statements and letters you\'ve received from us')
    expect(result.stack[4]).toHaveProperty('text', 'review the SFI scheme information at ')
    expect(result.stack[4]).toHaveProperty('text', 'www.gov.uk/government/collections/sustainable-farming-incentive-guidance')
    expect(result.stack[4]).toHaveProperty('link', 'https://www.gov.uk/government/collections/sustainable-farming-incentive-guidance')
    expect(result.stack[4]).toHaveProperty('listStyle', 'square')
    expect(result.stack[5]).toHaveProperty('text', 'If you have any questions about this email')
    expect(result.stack[6]).toHaveProperty('text', 'You can email ')
    expect(result.stack[6]).toHaveProperty('text', 'ruralpayments@defra.gov.uk')
    expect(result.stack[6]).toHaveProperty('link', 'mailto:ruralpayments@defra.gov.uk')
    expect(result.stack[6]).toHaveProperty('text', ' You can email ruralpayments@defra.gov.uk, adding SFI in the subject header of your email, or call us on 03000 200 301 (Monday to Friday, 8.30am to 5pm). Please tell us your SBI and Agreement number if applicable which are at the top of this email')
    expect(result.stack[7]).toHaveProperty('text', 'Yours faithfully ')
    expect(result.stack[7]).toHaveProperty('text', 'Karen Brash')
    expect(result.stack[7]).toHaveProperty('text', 'Sustainable Farming Incentive Operational Delivery manager')
    expect(result.stack[7]).toHaveProperty('text', 'Rural Payments Agency | PO Box 325 | WORKSOP | S95 1DE \n ruralpayments@defra.gov.uk | 03000 200 301 | gov.uk/defra/sfi \n Follow us on Twitter @Ruralpay')
  })
})
